---
version: 2
updates:
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "daily"
      assignees:
          - "ElBe-Plaq"
      labels:
          - "dependencies"
      commit-message:
          prefix: "chore(deps)"

    - package-ecosystem: "cargo"
      directory: "/"
      schedule:
          interval: "daily"
      assignees:
          - "ElBe-Plaq"
      labels:
          - "dependencies"
      commit-message:
          prefix: "chore(deps)"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      assignees:
          - "ElBe-Plaq"
      labels:
          - "dependencies"
      commit-message:
          prefix: "chore(deps)"

    - package-ecosystem: "gitsubmodule"
      directory: "/"
      schedule:
          interval: "daily"
      assignees:
          - "ElBe-Plaq"
      labels:
          - "dependencies"
      commit-message:
          prefix: "chore(deps)"
