---
autoCloseIssue: true
branchName: short
defaultBranch: "v1.0.0-alpha2" # Needs to be updated with every new update
branches:
    - label: question
      skip: true
    - label: no branch
      skip: true
