---
DISABLE_ERRORS_LINTERS:
    - SPELL_CSPELL
    - REPOSITORY_DEVSKIM # cspell:disable-line
    - MAKEFILE_CHECKMAKE # cspell:disable-line
    - HTML_HTMLHINT # cspell:disable-line
    - MARKDOWN_MARKDOWN_LINK_CHECK
    - REPOSITORY_DUSTILOCK # cspell:disable-line
    - JAVASCRIPT_STANDARD
    - REPOSITORY_TRUFFLEHOG # cspell:disable-line
    - SPELL_LYCHEE
FILTER_REGEX_EXCLUDE: .*mypy.* # cspell:disable-line
EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: "Docs/acknowledgements.md|src/Installer/Linux/installer.bash"
REPORT_OUTPUT_FOLDER: none
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: false
