---
DISABLE_ERRORS_LINTERS:
    - SPELL_CSPELL
    - REPOSITORY_DEVSKIM  # cspell:disable-line
    - MAKEFILE_CHECKMAKE # cspell:disable-line
    - HTML_HTMLHINT # cspell:disable-line
FILTER_REGEX_EXCLUDE: .*mypy.* # cspell:disable-line
EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: "Docs/acknowledgements.md"
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS_IF_LESS_THAN: 1
REPORT_OUTPUT_FOLDER: none
SHOW_ELAPSED_TIME: true
