repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-shebang-scripts-are-executable
          - id: check-toml
          - id: check-yaml
          - id: name-tests-test
            args: [--pytest-test-first]
          - id: pretty-format-json
            args: [--autofix]
          - id: requirements-txt-fixer
          - id: trailing-whitespace
    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.5
      hooks:
          - id: bandit
    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black
    - repo: https://github.com/pylint-dev/pylint
      rev: v3.0.0a6
      hooks:
          - id: pylint
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.0.262
      hooks:
          - id: ruff
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.2.0
      hooks:
          - id: mypy
    - repo: local
      hooks:
          - id: pytest-check
            name: pytest-check
            entry: pytest
            language: system
            pass_filenames: false
            always_run: true

ci:
  skip: [pytest-check]
