repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-shebang-scripts-are-executable
          - id: check-toml
          - id: check-yaml
          - id: name-tests-test
            args: [--pytest-test-first]
          - id: pretty-format-json
            args: [--autofix]
          - id: requirements-txt-fixer
          - id: trailing-whitespace
    - repo: https://github.com/doublify/pre-commit-rust
      rev: v1.0
      hooks:
          - id: fmt
          - id: cargo-check
          - id: clippy
