# Note:
# All edits to this file, for example rust version updates, should be committed only on a new release.

[package]
name = "I-Language"
description = "The I programming language is a high level programming language written in rust."
version = "1.0.0-alpha4"
authors = [
	"ElBe-Plaq <elbe.dev.plaq@gmail.com>",
	"MasterOktagon",
	"Ranastra"
]
edition = "2021"
rust-version = "1.69"
documentation = "https://i-language.readthedocs.io/"
readme = ".github/README.md"
homepage = "https://i-language-development.github.io/"
repository = "https://github.com/I-Language-Development/I-language-rust/"
license-file = "LICENSE.txt"
keywords = ["i", "i-language", "programming-language", "language", "compiler"]
categories = [
	"compilers",
	"development-tools",
]

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
current_locale = "0.1.1"
localizer-rs = "1.2.0"

lexer = { package = "I-Language-lexer", version = "1.0.0", path = "src/lexer" }
#parser = { package = "I-Language-parser", version = "1.0.0", path = "src/parser" }
tools = { package = "I-Language-tools", version = "1.0.0", path = "src/tools" }

[dev-dependencies]
just = "1.14.0"

[features]
beta = []

[lib]
name = "I_Language"
path = "src/lib.rs"

[[bin]]
name = "I_Language_CLI"
path = "src/main.rs"

