# Note:
# All edits to this file, for example rust version updates, should be committed only on a new release.

[package]
name = "I-Language-Rust"
description = "The I programming language is a high level programming language written in rust."
version = "1.0.0-alpha3"
authors = [
	"ElBe-Plaq <elbe.dev.plaq@gmail.com>",
	"MasterOktagon",
	"Ranastra"
]
edition = "2021"
rust-version = "1.69"
documentation = "https://i-language.readthedocs.io/"
readme = ".github/README.md"
homepage = "https://i-language-development.github.io/"
repository = "https://github.com/I-Language-Development/I-language-rust/"
license-file = "LICENSE"
keywords = ["i", "i-language", "programming-language", "language", "compiler"]
categories = [
	"compilers",
	"development-tools",
]

[dependencies]
pest = "2.7.3"
pest_derive = "2.7.3"

[dev-dependencies]
check = "1.0.0"
fmt = "0.1.0"
just = "1.14.0"
pest_fmt = "0.2.4"

[features]
beta = []
