---
site_name: I Language
repo_url: https://github.com/I-Language-Development/I-Language-Rust
site_description: The I programming language is a high level programming language written in rust.
site_author: I-Language-Development
copyright: Copyright (c) 2023-present I Language Development.
nav:
    - Home: index.md
    - About: about.md
    - Issues: https://github.com/I-Language-Development/I-Language-Rust/issues
theme:
  name: material
  icon:
      repo: fontawesome/brands/github
  features:
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
hooks:
    - Tools/Docs/replace_variables.py

