---
name: Create release
permissions: read-all

on:
    pull_request:
        types: [opened]
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.11
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"
            - name: Save version
              run: echo "RELEASE_VERSION=$(python Tools/get_release_version.py)" >> "$GITHUB_ENV" # cspell:disable-line
            - name: Create release
              uses: marvinpinto/action-automatic-releases@latest # cspell:disable-line
              if: ${{ startsWith(github.event.pull_request.title, '[UPDATE]') }} # cspell:disable-line
              with:
                  repo_token: ${{ secrets.PAT }} # cspell:disable-line
                  draft: true
                  automatic_release_tag: v${{ env.RELEASE_VERSION }}
                  title: v${{ env.RELEASE_VERSION }}
                  files: | # cspell:disable-next-line
                      .github/README.md
                      LICENSE.txt
                      src/Installer/Linux/installer.bash
                      src/Installer/Windows/Server/installer.bat
                      *.exe
