name: Rust
permissions: read-all

on: [push, pull_request]

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - name: Run tests
              run: cargo test --workspace
